### PR TITLE
Merge react progress into dev

### PR DESCRIPTION
**Pull request by jwsmith24**
Update Vite project to support TypeScript, begin defining data structures for Rubric and Criteria objects, create starting points for a home page and rubric builder view.

### CODE REVIEW

**Comment by jwsmith24** [comment]
Added a commit to fix issues with shallow copies not triggering React to re-render the rubric builder component.

**Comment by jwsmith24** [comment]
Also changed the home page back to being the first thing loaded.

**Comment by jwsmith24** [comment]
Refactored components into own files and used React props how they're actually supposed to be used :joy:

**Review by benaspinall1 — COMMENTED** [review]
• Comments are comprehensible and add something to the maintainability of the code (trivial comments do not help, rather write readable code) 
	- For the active Boolean in Criteria.ts I don't get toggle view vs widget view. At first glance it seems to be saying that the criteria can be active or not but your comment makes me 	think otherwise.
 	- I think you should add a global comment to initializeRatings. Ratings are unclear at the comment level.
	- I think you should comment all of the props interfaces and maybe even the event handler methods.

    • Comments are neither too numerous nor verbose
	- See suggestions above.
    • Types have been generalized where possible
	- Good.
    • Parameterized types have been used appropriately
	- Good.
    • Exceptions have been used appropriately
	- Remove criterion, update criterion, and get criterion should throw exceptions if out of bounds. 
    • Repetitive code has been factored out
	- Good.
    • Frameworks have been used appropriately - methods have all been defined appropriately
	- I'm still a little slow with typescript and react so for example I don't really understand the CriteriaInput file completely. Again for example, in handleRemoveCriteria what is 	prevent default doing and why don't you call remove criterion from the Rubric file? (Or maybe that's what it does.. (I'll get there))
    • Command classes have been designed to undertake one task only
	- Good
    • ISPs do not contain business logic
	- Good
    • Unit tests are present and correct
	- No tests.
    • Common errors have been checked for
	- No tests.
    • Potential threading issues have been eliminated where possible
	- Good.

**Review by benaspinall1 — COMMENTED** [review]
• Comments are comprehensible and add something to the maintainability of the code (trivial comments do not help, rather write readable code) 
- Good
• Comments are neither too numerous nor verbose
- Good
• Types have been generalized where possible
- Good.
• Parameterized types have been used appropriately
- Good.
• Exceptions have been used appropriately
- Good.
• Repetitive code has been factored out
- Good.
• Frameworks have been used appropriately - methods have all been defined appropriately
- Good.
• Command classes have been designed to undertake one task only
- Good
• ISPs do not contain business logic
- Good
• Unit tests are present and correct
- No tests.
• Common errors have been checked for
- No tests.
• Potential threading issues have been eliminated where possible
- Good.

**Review by benaspinall1 — APPROVED** [review]

**Pull request merged**
